// config.bin - 22:55:55 07/14/10, generated in 0.12 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

#define private		0
#define protected		1
#define public		2

#define true	1
#define false	0

enum {
	STABILIZEDINAXISX = 1,
	STABILIZEDINAXISY = 2,
	STABILIZEDINAXESBOTH = 3,
	STABILIZEDINAXESNONE = 0,
};

class CfgPatches {
	class LEN_Backpacks {
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"CAWeapons"};
	};
};

class cfgVehicles {
	class ReammoBox;	// External class reference
	class ReammoBox_EP1;	// External class reference
	class Bag_Base_EP1;	// External class reference
		
	class LEN_Backpack_OD : Bag_Base_EP1 {
		scope = public;
		displayName = "Backpack (OD)";
		picture = "\ca\weapons_e\data\icons\backpack_ACR_CA.paa";
		icon = "\ca\weapons_e\data\icons\mapIcon_backpack_CA.paa";
		mapsize = 2;
		model = "\len_backpacks\backpack_odr.p3d";
		transportMaxWeapons = 1;
		transportMaxMagazines = 14;
	};

	class LEN_Backpack_DES : LEN_Backpack_OD {
		displayName = "Backpack (Des)";
		model = "\len_backpacks\backpack_des.p3d";
	};

	class LEN_Backpack_3DES : LEN_Backpack_OD {
		displayName = "Backpack (3 Color Desert)";
		model = "\len_backpacks\backpack_3ds.p3d";
	};

	class LEN_Backpack_WDL : LEN_Backpack_OD {
		displayName = "Backpack (M81 Woodland)";
		model = "\len_backpacks\backpack_wdl.p3d";
	};

	class LEN_Backpack_MAR : LEN_Backpack_OD {
		displayName = "Backpack (Marpat Woodland)";
		model = "\len_backpacks\backpack_mar.p3d";
	};

	class LEN_Backpack_DMAR : LEN_Backpack_OD {
		displayName = "Backpack (Marpat Desert)";
		model = "\len_backpacks\backpack_dmr.p3d";
	};

	class LEN_Backpack_UCP : LEN_Backpack_OD {
		displayName = "Backpack (UCP)";
		model = "\len_backpacks\backpack_ucp.p3d";
	};

	class LEN_Backpack_6DES : LEN_Backpack_OD {
		displayName = "Backpack (6 Color Desert)";
		model = "\len_backpacks\backpack_6ds.p3d";
	};

	class LEN_Backpack_TAK : LEN_Backpack_OD {
		displayName = "Backpack (Takistani DPM)";
		model = "\len_backpacks\backpack_tak.p3d";
	};

	class LEN_Backpack_NVG : LEN_Backpack_OD {
		displayName = "Backpack (NVG Camo)";
		model = "\len_backpacks\backpack_nvg.p3d";
	};

	class LEN_Backpack_BLK : LEN_Backpack_OD {
		displayName = "Backpack (Black)";
		model = "\len_backpacks\backpack_blk.p3d";
	};

	class LEN_Backpack_DPM : LEN_Backpack_OD {
		displayName = "Backpack (British DPM)";
		model = "\len_backpacks\backpack_dpm.p3d";
	};

	class LEN_Backpack_FIN : LEN_Backpack_OD {
		displayName = "Backpack (Finnish M05)";
		model = "\len_backpacks\backpack_fin.p3d";
	};

	class LEN_Backpack_MTC : LEN_Backpack_OD {
		displayName = "Backpack (Multicam)";
		model = "\len_backpacks\backpack_mtc.p3d";
	};

	class LEN_Backpack_NOR : LEN_Backpack_OD {
		displayName = "Backpack (Digital Pattern)";
		model = "\len_backpacks\backpack_nor.p3d";
	};

	class LEN_Backpack_WIN : LEN_Backpack_OD {
		displayName = "Backpack (Winter)";
		model = "\len_backpacks\backpack_win.p3d";
	};

	class LEN_Backpack_ATC : LEN_Backpack_OD {
		displayName = "Backpack (ATACS)";
		model = "\len_backpacks\backpack_atc.p3d";
	};

	class LEN_Backpack_MTL : LEN_Backpack_OD {
		displayName = "Backpack (Mitchell Pattern)";
		model = "\len_backpacks\backpack_mtl.p3d";
	};

	class LEN_Backpack_FTN : LEN_Backpack_OD {
		displayName = "Backpack (Fictional Flecktarn)";
		model = "\len_backpacks\backpack_ftn.p3d";
	};
		
};
